name: Deploy

on:
  push:
    tags: [v*.*.*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Get version
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG} .
    
    - name: Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push
      run: docker push ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG}
